#datasource specific properties
spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3307/traingingDB
    username: root
    password: Appneura@123
    
#jpa specific properties
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create